Repository Clueless-Community/fintech-api, pull requests merged in 2023-07, with the labels that each got.

#379 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: gssoc23, level2

#394 [Fixes #384] Removed redundant compounded annual growth rate endpoint
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/compound_annual_growth_rate.py
  tasks/compounded_annual_growth_rate.py
  tests/test_main.py
Labels: gssoc23, level2

#396 Code Formatting GitHub Workflow Created ✔
  .github/workflows/lint.yml
Labels: gssoc23, level2

#399 fixing some bugs in endpoints ( Issue: #367 ) & Adding Endpoint to calculate Capital Asset Pricing Model (CAPM) ( Issue: #368)
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/calculate_capm.py
  tasks/credit_card_payoff.py
  tasks/price_to_earning_ratio.py
  tasks/sharpe_ratio.py
  validators/request_validators.py
Labels: gssoc23, level3

#404 Debt service coverage ratio
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/debt_service_coverage_ratio.py
  validators/request_validators.py
Labels: gssoc23, level3

#400 Removing duplicate classes from request_validators.py ( Issue : #389 )
  validators/request_validators.py
Labels: gssoc23, level3

#410 Defensive interval ratio
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/defensive_interval_ratio.py
  validators/request_validators.py
Labels: gssoc23, level3

#413 Added endpoints and functions to calculate profit and loss percentage
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/loss_percentage.py
  tasks/profit_percentage.py
  validators/request_validators.py
Labels: gssoc23, level2

#430 edited the lumpsum error
  Readme.md
  main.py
  tasks/lumpsum.py
Labels: gssoc23, level1

#426 Financial assest ration is added
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/financialAssestRatio.py
  validators/request_validators.py
Labels: gssoc23, level3

#438 422 error on treynor_ratio
  main.py
Labels: gssoc23, level1

#433 Cash Conversion Cycle
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/cash_conversion_cycle.py
  validators/request_validators.py
Labels: gssoc23, level3

#445 Price Elasticity endpoint is added
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/PriceElasticity.py
  validators/request_validators.py
Labels: gssoc23, level3

#441 Policy premium endpoint is added
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/PolicyPremium.py
  validators/request_validators.py
Labels: gssoc23, level3

#455 Average payment period
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/average_payment_period.py
  validators/request_validators.py
Labels: gssoc23, level3

#469 docs: Added GSSoC 2K33 in open-source programs section
  Readme.md
Labels: gssoc23, level1

#463 [Fixes: #414] Added Endpoint to Calculate MIRR
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/modified_internal_rate_of_return.py
  tests/test_main.py
  validators/request_validators.py
Labels: gssoc23

#478 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc23, level3

#457 [ADDED]: Saving Goal Endpoint
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/Saving_Goal.py
  validators/request_validators.py
Labels: gssoc23, level3
