Repository Clueless-Community/fintech-api, pull requests merged in 2023-08, with the labels that each got.

#490 README.md enhanced
  Readme.md
Labels: gssoc23, level1

#480 Interest coverage ratio
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/interest_coverage_ratio.py
  validators/request_validators.py
Labels: gssoc23, level3

#494 feat: Update docker-compose.yml
  docker-compose.yml
Labels: gssoc23, level2

#493 Margin of safety
  DOCUMENTATION.md
  ENDPOINTS.md
  helpers/functions.py
  main.py
  tasks/margin_of_safety.py
  validators/request_validators.py
Labels: gssoc23, level3

#502 feat: modified pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: gssoc23, level1
