Repository Clueless-Community/fintech-api, pull requests merged in 2023-06, with the labels that each got.

#326 Endpoint to calculate Net annual salary
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#310 Added black linter workflow
  .github/workflows/black.yml
  helpers/functions.py
  test_main.py
Labels: gssoc23, level2

#329 Added Treynor Ratio function
  ENDPOINTS.md
  helpers/functions.py
  main.py
  test_main.py
Labels: gssoc23, level3

#330 Added endpoint for post tax return
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#331 Added Loan To Value Ratio
  ENDPOINTS.md
  helpers/functions.py
  main.py
  requirements.txt
Labels: gssoc23, level2

#320 Development2
  .hypothesis/unicode_data/13.0.0/charmap.json.gz
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#347 Create auto-comment.yml
  .github/workflows/auto-comment.yml
Labels: gssoc23, level3

#348 corrected all errors
  helpers/functions.py
  main.py
Labels: gssoc23, level2

#358 Adding unit-tests for all end-points [Issue : #231]
  test_main.py
Labels: gssoc23, level2

#365 Added an endpoint for networth calculation
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level2

#375 Added dependabot.yml file
  .github/dependabot.yml
Labels: gssoc23, level3

#378 Added monte carlo functionality on portfolio
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#383 [Fixes #376] Removed redundant Sharpe Ratio Endpoint
  main.py
Labels: gssoc23, level1
