Repository Clueless-Community/fintech-api, pull requests merged in 2023-05, with the labels that each got.

#225 Corrected the Errors present in the main.py file
  main.py
Labels: GSSOC23

#237 Added the changes based on the issue #226
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: GSSOC23

#250 Updated Endpoints in main.py
  main.py
Labels: GSSOC23

#253 back to top button added
  README.md
Labels: gssoc23, level1

#257 Created an endpoint to Calculate Student loan
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#259 Created endpoint for calculating annual income needed during retireme…
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#261 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc23, level1

#263 Added new templates for issues template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/OTHER_ISSUE.md
Labels: gssoc23, level2

#269 added VAT #260
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level2

#273 Created Endpoint for Annual Debt Service Coverage Ratio (ADSCR) and fixed minor bug
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level2

#274 Adding .dockerignore file
  .dockerignore
Labels: gssoc23, level2

#280 Fix #278: Improve Issue Templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/OTHER_ISSUE.md
Labels: gssoc23, level1

#284 New feature loan affordability
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#286 Fix #271 by correcting the effective_annual_rate function name
  main.py
Labels: gssoc23, level2

#288 Add utility functions to convert from percent to decimal and vice versa
  helpers/functions.py
  helpers/utils.py
  main.py
Labels: gssoc23, level2

#291 Feature added to calculate BVPS (book value per share)
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#289 adding functionality of market capitalization
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#299 added gratuity calculator
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#303 Endpoint to calculate accrued interest
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3

#306 Endpoint to Calculate Simple personal savings
  ENDPOINTS.md
  helpers/functions.py
  main.py
Labels: gssoc23, level3
